### ISSUE TITLE
Why is nobody using this?

### ISSUE THREAD

**Issue by flowerornament** [codeboost/bea#1]
This seems like a panacea, and JOpenFrameworks as well. Why have these projects not taken off? Is it a matter of lack of marketing, have they been superseded by other projects, are there downsides that are not immediately apparent? Being able to very easily use C++ from V8 seems like something that people would be all over, especially since, as I understand, the FFI is not very good.

**Comment by codeboost** [comment]
Good question. I guess it's a combination of lack of marketing and that it looks too 'magical' to be true :).
I've used this technology to script 3 large C++ frameworks - OpenFrameworks, OpenCV and the partially, JUCE C++ GUI as well as for some smaller libraries. With a bit of tweaking it can also be used to expose C++ libraries to node.js.

**Comment by colormotor** [comment]
Hi, this looks amazing, but I can't figure out how to run the converter from the command line in osx.
do I have to call bea through Jsc?

**Comment by codeboost** [comment]
Yeah, it's been gathering dust for some time. But since there is at least one person on this planet who's interested in it, I'll quickly clean it up and commit an update.

**Comment by colormotor** [comment]
very interested! ill try to spread the word if it works

**Comment by codeboost** [comment]
Ok, so I've pushed an update - cleaned up and added a demo project (examples/hello). There's README.md which describes the build steps (OSX and Linux for now).
I've also updated the bea/README.md file which explains how to install and run it.

Good luck, let me know if it worked !

**Comment by colormotor** [comment]
Hey thanks alot!
seems like it's working, still have to get it running in V8 but that will take a bit longer, will keep you posted

For the moment I had some little problems:
- Coffee was complaining about public being a reserved word in classconvert.coffee, I changed the variable public to pub and everything worked...
- Had to change the required path in bea.coffee to the get it working from the folder where I was working, maybe theres a cleaner way to do this?
- I'm sometimes using nested namespaces in my project, does bea handle that?

but I have the feeling this will save me lots of time!

**Comment by colormotor** [comment]
actually no problems with nested namespaces....

**Comment by codeboost** [comment]
Ok, thanks for the update.
I've fixed the use of 'public' as a variable name - I had CoffeeScript 1.2 on my system and it seemed to work..

You shouldn't need to change the path. Go to your target directory (eg. were your project is) and call bea relatively, (take a look at examples/hello/bea.sh). 

Not sure about the nested namespaces, did it work ?

**Comment by colormotor** [comment]
hey this is just great... 
in a couple of days I already have a repl and scripting in my engine.
Getting nested namespaces to work takes a bit extra effort, because I have to often specify the namespace of classes, but it's not a big problem

**Comment by codeboost** [comment]
> > Getting nested namespaces to work takes a bit extra effort

Try using typedefs to shorten the names. Bea is a code generator, not a compiler, it doesn't really understand what a namespace is. So you can give it anything as long as the C++ compiler can figure it out. For instance:

```
namespace One{
    namespace Two{
        class MyClass{}...  
    }
}
```

You can typedef your objects-to-be-exposed in a separate namespace and feed that to bea:

```
namespace JS{
typedef One::Two::MyClass MyClass;  
}
```

Then, use the JS namespace in your .bea file. Bea will spit out the generated code and as long as the compiler can figure out the types, you should be ok.

Hope this helps. I'm going to close this issue now.
