### ISSUE TITLE
static class methods

### ISSUE THREAD

**Issue by colormotor** [codeboost/bea#4]
Would be nice to automatically handle static methods on classes :)
It seems that right now I have to declare @static methods with a different class name, otherwise the C++ compiler complains...

**Comment by codeboost** [comment]
It does handle static functions. Just declare the function as static in the bea file:

```
static std::string className()
```

I think the confusion comes from the use of '@static' keyword in the class declaration. '@static' means static class, or better, static object, which cannot be instantiated by Javascript, but you can call it's methods from JS.
That would be some global object in your C++ code or plain C functions.
